# Generated by Django 3.2.8 on 2021-11-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=19)),
                ('proprietario', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.TimeField()),
                ('loja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
        ),
    ]
