# Generated by Django 3.2.8 on 2021-11-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='loja_id',
            new_name='loja',
        ),
    ]
