# Generated by Django 3.2.8 on 2021-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_loja_id_operacao_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
